hash-format = "sha256"

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "9958fb387df596f96a5b6b0a12f3def77dd75d9ae3781709b6510744fd98db98"
metafile = true

[[files]]
file = "mods/jcm.pw.toml"
hash = "385590390867eeccae3533f852794d2abe0b19f928ef30a88765ea4c4cb7c0b3"
metafile = true

[[files]]
file = "mods/minecraft-transit-railway.pw.toml"
hash = "9751fac0f672b632c9d249528c2749769b8edb3e3e880ac82c583723a7e11937"
metafile = true

[[files]]
file = "mods/mtr-nte.pw.toml"
hash = "5b3054a11c654df4c24841d36649534aa205b15ba3009315eb58929275d7f31e"
metafile = true

[[files]]
file = "mods/reality-c-c.pw.toml"
hash = "c7dacc6641055562775c1f8ac633a6745e40bee1b21d47f9561571c2595d248f"
metafile = true

[[files]]
file = "mods/station-decoration.pw.toml"
hash = "ff8a60510a0b74d5bab2acd2f57fe2c7144886195eae3b2446b341409db675ac"
metafile = true

[[files]]
file = "mods/the-tube.pw.toml"
hash = "4114b6b8e08c91b8c6da887658189d2ee761526d378923a49b38352879507b1e"
metafile = true

[[files]]
file = "mods/time-wind.pw.toml"
hash = "1d5e234837f3a624aea181144f88cdb99ce4ca4ac50761ff7c62870cd333d83a"
metafile = true
